;--------------------------------------------------------------------------------------------
; SIDEBAR MUSIC COMMENTS

;----------------------------------------------
; NORMAL

[StyleMusicNormalBackground]
H=152

[StyleMusicNormalBorder]
SolidColor=#ColorBorder4#
X=10
Y=5
W=(#SidebarWidth#-120)
H=1
Hidden=#HideBordersTop#

[StyleMusicNormalHeader]
X=(#SidebarWidth#-10)
Y=1
FontColor=#Color1#
FontFace=#Font#
FontSize=#Size3#
StringAlign=RIGHT
StringStyle=NORMAL
Text="C o m m e n t s"
AntiAlias=1
Hidden=#HideBordersTop#

[StyleMusicNormalCurtain]
X=0
Y=0
W=0
H=0
Hidden=1

[StyleMusicNormalText]
X=14
Y=16r
H=15
W=(#SidebarWidth#-28)
ClipString=1
FontFace=#Font#
FontSize=#Size3#
StringAlign=LEFT
StringStyle=NORMAL
AntiAlias=1

[StyleMusicNormalTextFirst]
FontColor=#Color1#
Y=16

[StyleMusicNormalButton]
X=16r
Y=49
W=10
H=10
AntiAlias=1
Hidden=1
Group=EnigmaMouseover